import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import { setDefaultResultOrder } from 'dns'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [data, setData] = useState<any>();
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<any>(null);

   useEffect(() => {
    fetch('api/hello')
    .then(response => {
      if(response.ok) {
        return response.json()
      }
      throw response
    })
    .then(data => setData(data))
    .catch(error => {
      console.error("error fetching name", error)
      setError(error);
    })
    .finally(() => { 
      setLoading(false)
    })
  }, [])

  if(loading) return "Loading..."
  if(error) return "error..."

  return (
    <>
      <Head>
        <title>Sports Motor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>{data.name}</div>
      </main>
    </>
  )
}
