import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

const getHello = async ()=>  {
  const helloRes = await fetch('api/hello').then((response) => response.json())
  return helloRes
}

export default function Home() {
  const [name, setName] = useState('');

  //this doesn't work because useEffect is not async
  useEffect(() => {
    getHello().then(data => setName(data))
  }, [])


  return (
    <>
      <Head>
        <title>Sports Motor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>{name}</div>
      </main>
    </>
  )
}
